stages:
  - linting
  - test

flake8:
  stage: linting
  image: python:3.7
  before_script:
    - pip install flake8
  script:
    - flake8 .

.nose2:
  before_script:
    - apt-get update
    - apt-get install libboost-system-dev tesseract-ocr build-essential git cmake -y
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - git submodule update --init --recursive
    - python3 setup.py build_ext
    - mkdir temp
    - mkdir temp1
    - mkdir temp2
    - unzip data/charts_steph.zip -d data
    - unzip data/charts_steph_upscaled.zip -d data
  script:
    - python3 -m nose2 --start-dir tests/ --with-coverage
    - python3 -m coverage xml --fail-under 0
  artifacts:
    reports:
      cobertura: coverage.xml
  only:
    - merge_requests
    - tags
    - master

nose2-3.7-buster:
  extends: .nose2
  stage: test
  image: python:3.7-buster

nose2-3.8-buster:
  extends: .nose2
  stage: test
  image: python:3.8-buster

nose2-3.9-bullseye:
  extends: .nose2
  stage: test
  image: python:3.9-bullseye

nose2-3.10-bullseye:
  extends: .nose2
  stage: test
  image: python:3.10-bullseye
