stages:
  - linting
  - test

flake8:
  stage: linting
  image: python:3.7
  before_script:
    - pip install flake8
  script:
    - flake8 .

nose2:
  stage: test
  image: python:3.7-buster
  before_script:
    - pip install -r requirements.txt
  script:
    - python3 -m nose2 --start-dir tests/
