stages:
  - linting
  - test

flake8:
  stage: linting
  image: python:3.7
  before_script:
    - pip install flake8
  script:
    - flake8 .

nose2:
  stage: test
  image: python:3.7-buster
  before_script:
    - sudo apt update
    - sudo apt install libboost-system-dev tesseract-ocr build-essential git
    - pip install -r requirements.txt
    - git submodule update --init --recursive
    - python3 setup.py build_ext
    - mkdir lib
    - sudo python3 setup.py install --install-lib lib/
    - mkdir temp
    - mkdir temp1
    - mkdir temp2
    - unzip data/charts_steph.zip -d data
  script:
    - python3 -m nose2 --start-dir tests/
